### ISSUE TITLE
小BUG

### ISSUE THREAD

**Issue by passioncsu** [WangYihang/UsbKeyboardDataHacker#1]
43行稍微改一下吧
if Bytes[2] != "00" and normalKeys.get(Bytes[2]):
加个判断，不然报错执行不下去，反正我这边是这样的情况

**Comment by WangYihang** [comment]
收到 , 不好意思最近比较忙 , 现在才回复
其实有一点挺奇怪的我一直没有弄清楚
就是 Tshark 导出的数据似乎不止是键盘的流量 , 可能还有鼠标等别的USB设备的流量
所以生成的数据文件中有一部分是不可用的
应该是过滤的参数不对 , 但是现在还没有正确的参数
我抽时间找找解决方案

**Comment by WangYihang** [comment]
Fixed.
