### ISSUE TITLE
无法正确处理shift按下的情况

### ISSUE THREAD

**Issue by ChristopherKai** [WangYihang/UsbKeyboardDataHacker#2]
带有shift按键流量包，提取出来无对应按键。
判断shift按键行的代码应该修改为
`elif int(Bytes[0],16) & 0b10 or int(Bytes[0],16) & 0b10000: `
检测左右shift按键按下的情况。

**Comment by WangYihang** [comment]
收到！感谢师傅提醒！可以麻烦师傅开一个 Pull Request 吗？
